//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.WCF.Fifth {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.Fifth.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/PublicOperation", ReplyAction="http://tempuri.org/IService/PublicOperationResponse")]
        void PublicOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/RestrictedOperation", ReplyAction="http://tempuri.org/IService/RestrictedOperationResponse")]
        void RestrictedOperation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/AdminOperation", ReplyAction="http://tempuri.org/IService/AdminOperationResponse")]
        void AdminOperation();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : Client.WCF.Fifth.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<Client.WCF.Fifth.IService>, Client.WCF.Fifth.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PublicOperation() {
            base.Channel.PublicOperation();
        }
        
        public void RestrictedOperation() {
            base.Channel.RestrictedOperation();
        }
        
        public void AdminOperation() {
            base.Channel.AdminOperation();
        }
    }
}
